"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Optionally load .env (install python-dotenv and create .env in project root)
try:
    from dotenv import load_dotenv  # optional
    load_dotenv()
except Exception:
    # python-dotenv not required; environment variables still used if present
    pass

# BASE_DIR (project root)
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------
# Security & environment
# ------------------------
# SECRET_KEY should always come from environment in production
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-replace-me-with-a-secure-value-for-prod"  # fallback for local/dev only
)

# DEBUG should be False in production
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

# When deploying to production, set ALLOWED_HOSTS env var with comma-separated hosts
_allowed_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

# ------------------------
# Application definition
# ------------------------
INSTALLED_APPS = [
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",                       # Django REST Framework
    "corsheaders",                          # CORS for React dev server

    # Your apps
    "great_balladis",                                  # example API app (create this)
]

MIDDLEWARE = [
    # CORS middleware must be high so it can add headers on responses
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Add BASE_DIR / 'templates' here if you want project-level templates
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

WSGI_APPLICATION = "backend.wsgi.application"

# ------------------------
# Database
# ------------------------
# Default: local sqlite. For production set DATABASE_URL or individual env vars.
if os.environ.get("DATABASE_URL"):
    # Example: you can use dj-database-url in production to parse DATABASE_URL
    # But to keep dependencies minimal, expect you will configure DATABASES externally.
    # If you use dj-database-url, parse DATABASE_URL here.
    pass

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DJANGO_DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DJANGO_DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DJANGO_DB_USER", ""),
        "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", ""),
        "HOST": os.environ.get("DJANGO_DB_HOST", ""),
        "PORT": os.environ.get("DJANGO_DB_PORT", ""),
    }
}

# For Postgres in production, set:
# DJANGO_DB_ENGINE=django.db.backends.postgresql
# DJANGO_DB_NAME=yourdbname
# DJANGO_DB_USER=yourdbuser
# DJANGO_DB_PASSWORD=secret
# DJANGO_DB_HOST=db-host
# DJANGO_DB_PORT=5432

# ------------------------
# Password validation
# ------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------
# Internationalization / timezone
# ------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Africa/Accra")
USE_I18N = True
USE_TZ = True

# ------------------------
# Static & Media files
# ------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"]  # for local dev: keep your React build here if serving via Django

MEDIA_URL = "/media/"
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / "media")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------
# Django REST Framework & JWT (SimpleJWT)
# ------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # add 'rest_framework.authentication.SessionAuthentication' if you want session-based auth
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Install djangorestframework-simplejwt and customize token lifetime here:
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES", 30))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS", 7))),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ------------------------
# CORS (for React dev server)
# ------------------------
# In development allow localhost:3000 (React). In production set DJANGO_CORS_ALLOWED_ORIGINS.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# Optionally allow credentials (if you use cookies)
CORS_ALLOW_CREDENTIALS = True

# If you want to allow all origins in local dev (not recommended in prod) you can set:
# CORS_ALLOW_ALL_ORIGINS = True

# ------------------------
# Security-related settings (tweak for production)
# ------------------------
# Use secure cookies & other settings when running under HTTPS
SESSION_COOKIE_SECURE = os.environ.get("DJANGO_SESSION_COOKIE_SECURE", "False").lower() in ("1", "true")
CSRF_COOKIE_SECURE = os.environ.get("DJANGO_CSRF_COOKIE_SECURE", "False").lower() in ("1", "true")
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "False").lower() in ("1", "true")

# Example: set CSRF_TRUSTED_ORIGINS in production to include your site(s)
_csrf_trusted = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [u.strip() for u in _csrf_trusted.split(",") if u.strip()]

# ------------------------
# Logging (basic)
# ------------------------
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(levelname)s %(asctime)s %(name)s %(message)s"},
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
}

# ------------------------
# # Helpful development flags
# # ------------------------
# # Show Django debug toolbar if installed and DEBUG True (optional)
# if DEBUG:
#     try:
#         import debug_toolbar  # noqa: F401
#         INSTALLED_APPS += ["debug_toolbar"]
#         MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
#         INTERNAL_IPS = ["127.0.0.1"]
#     except Exception:
#         # debug-toolbar not installed; ignore
#         pass